require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - node_modules/**/*

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitSubject:
   Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

Capybara/FeatureMethods:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/api/**/*

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/EmptyMethod:
  EnforcedStyle: expanded
  SupportedStyles:
    - compact
    - expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringMethods:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  SupportedStylesAlignWith:
    - keyword
    - variable

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
