require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - lib/templates/**/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/EmptyMethod:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Metrics/BlockLength:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringMethods:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false
  
Style/ClassAndModuleChildren:
  Enabled: false
