version: 2.1

jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Setup
          command: bin/setup

      - run:
          name: Test
          command: bin/ci
