defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  timeout: 5000
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  database: <%= ENV.fetch("DB_NAME", "#{File.basename(Rails.root)}_dev") %>
  <<: *defaults

test:
  database: <%= ENV.fetch("DB_NAME", "#{File.basename(Rails.root)}_test") %>
  <<: *defaults

production: &deploy
  database: <%= ENV.fetch("DB_NAME", "#{File.basename(Rails.root)}_production") %>
  <<: *defaults

staging: *deploy
