Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - lib/templates/**/*
    - vendor/**/*

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Bundler/OrderedGems:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Rails/FilePath:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
